### ISSUE TITLE
Problems when running angularjs-example-using-a-java-restful-web-service excample

### ISSUE THREAD

**Issue by Zilev** [draptik/angulardemorestful#6]
I'm trying to run the angularjs-example-using-a-java-restful-web-service excample with **java-backend** but I'm having problems when I do `mvn exec:java` I have:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project ngdemo: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java are missing or invalid -> [Help 1]
```

Someone can help me please?, thanks in advance :smile:

**Comment by draptik** [comment]
Does the code provided with the tag referenced in the blog work?

**Comment by draptik** [comment]
Some Maven error... I'll just close this
